/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExTestButton {
        /**
          * Whether the button is disabled.
          * @default false
         */
        "disabled": boolean;
        /**
          * Text content of the button.
          * @default "Button"
         */
        "label": string;
        /**
          * Visual style variant.
          * @default "primary"
         */
        "variant": "primary" | "secondary" | "outline";
    }
}
export interface ExTestButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLExTestButtonElement;
}
declare global {
    interface HTMLExTestButtonElementEventMap {
        "exTestClick": void;
    }
    interface HTMLExTestButtonElement extends Components.ExTestButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLExTestButtonElementEventMap>(type: K, listener: (this: HTMLExTestButtonElement, ev: ExTestButtonCustomEvent<HTMLExTestButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLExTestButtonElementEventMap>(type: K, listener: (this: HTMLExTestButtonElement, ev: ExTestButtonCustomEvent<HTMLExTestButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLExTestButtonElement: {
        prototype: HTMLExTestButtonElement;
        new (): HTMLExTestButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ex-test-button": HTMLExTestButtonElement;
    }
}
declare namespace LocalJSX {
    interface ExTestButton {
        /**
          * Whether the button is disabled.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Text content of the button.
          * @default "Button"
         */
        "label"?: string;
        /**
          * Fired when the button is clicked.
         */
        "onExTestClick"?: (event: ExTestButtonCustomEvent<void>) => void;
        /**
          * Visual style variant.
          * @default "primary"
         */
        "variant"?: "primary" | "secondary" | "outline";
    }

    interface ExTestButtonAttributes {
        "label": string;
        "variant": "primary" | "secondary" | "outline";
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "ex-test-button": Omit<ExTestButton, keyof ExTestButtonAttributes> & { [K in keyof ExTestButton & keyof ExTestButtonAttributes]?: ExTestButton[K] } & { [K in keyof ExTestButton & keyof ExTestButtonAttributes as `attr:${K}`]?: ExTestButtonAttributes[K] } & { [K in keyof ExTestButton & keyof ExTestButtonAttributes as `prop:${K}`]?: ExTestButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ex-test-button": LocalJSX.IntrinsicElements["ex-test-button"] & JSXBase.HTMLAttributes<HTMLExTestButtonElement>;
        }
    }
}
