/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExButton {
        /**
          * Whether the button is disabled.
          * @default false
         */
        "disabled": boolean;
        /**
          * Text content of the button.
          * @default "Button"
         */
        "label": string;
        /**
          * Visual style variant.
          * @default "primary"
         */
        "variant": "primary" | "secondary" | "outline";
    }
}
export interface ExButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLExButtonElement;
}
declare global {
    interface HTMLExButtonElementEventMap {
        "exClick": void;
    }
    interface HTMLExButtonElement extends Components.ExButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLExButtonElementEventMap>(type: K, listener: (this: HTMLExButtonElement, ev: ExButtonCustomEvent<HTMLExButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLExButtonElementEventMap>(type: K, listener: (this: HTMLExButtonElement, ev: ExButtonCustomEvent<HTMLExButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLExButtonElement: {
        prototype: HTMLExButtonElement;
        new (): HTMLExButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ex-button": HTMLExButtonElement;
    }
}
declare namespace LocalJSX {
    interface ExButton {
        /**
          * Whether the button is disabled.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Text content of the button.
          * @default "Button"
         */
        "label"?: string;
        /**
          * Fired when the button is clicked.
         */
        "onExClick"?: (event: ExButtonCustomEvent<void>) => void;
        /**
          * Visual style variant.
          * @default "primary"
         */
        "variant"?: "primary" | "secondary" | "outline";
    }

    interface ExButtonAttributes {
        "label": string;
        "variant": "primary" | "secondary" | "outline";
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "ex-button": Omit<ExButton, keyof ExButtonAttributes> & { [K in keyof ExButton & keyof ExButtonAttributes]?: ExButton[K] } & { [K in keyof ExButton & keyof ExButtonAttributes as `attr:${K}`]?: ExButtonAttributes[K] } & { [K in keyof ExButton & keyof ExButtonAttributes as `prop:${K}`]?: ExButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ex-button": LocalJSX.IntrinsicElements["ex-button"] & JSXBase.HTMLAttributes<HTMLExButtonElement>;
        }
    }
}
