// Re-export Angular component proxies generated by `packages/ui` Stencil build.
// Run `pnpm --filter @expressthat-auth/ui build` to generate this directory.

export * from "./components.module";
export * from "./generated/index";
